### ISSUE TITLE
fails to run, no package.json

### ISSUE THREAD

**Issue by ammraleigh** [monsterkodi/kalk#1]
[npm-debug.log](https://github.com/monsterkodi/kalk/files/2238671/npm-debug.log)

**Comment by monsterkodi** [comment]
hello ammraleigh,

no, there is no package.json. 

If you want to build **kalk** from the sources I suggest you try the following:

`npm install -g konrad`

then cd to the project folder and execute

`konrad -r`

this will generate the `package.json` and transpile all sources.
