### ISSUE TITLE
New design for the logo.

### ISSUE THREAD

**Issue by radudang** [monsterkodi/kalk#2]
Hello! I'm a professional graphic designer, and in my spare time I love to work on nice projects. I saw your logo and it looks outdated. I would like to give you an alternative for it. If you are interested please respond to that message here with an email on radudangratian@gmail.com. 
Regards!

**Comment by monsterkodi** [comment]
hi radudang,
you are right, I didn't put much effort into that logo ;-)
I am open for suggestions, you can post them here or send it to monsterkodi@gmx.net

**Comment by radudang** [comment]
Hello! I upload the concept here as soon they are ready.

**Comment by monsterkodi** [comment]
Cool, I am looking forward to it.

**Comment by monsterkodi** [comment]
hi @radudang 

I will close this issue for now.

But that shouldn't stop you from submitting a nice logo ;-)
